-- ============================================================
-- THE LAST GAME — additional short-form beats (seq 17–25)
-- Cut from the memoir's trial / prison / redemption chapters.
-- Applied to project "Base" (qgbjiqdwzgkjkmqyjsmc).
-- Re-runnable: on conflict (slug) do nothing.
-- ============================================================
insert into public.tlg_segments (seq, slug, title, hook_line, narration, caption, hashtags, thumbnail_prompt)
select (ord)::int, slug, title, hook_line, narration, caption,
       (select array_agg(x) from jsonb_array_elements_text(tags) x), thumbnail_prompt
from jsonb_to_recordset($json$[
{"ord":17,"slug":"railroaded","title":"The Judge Banned the Word CIA From His Trial","hook_line":"The judge banned the word CIA from his own trial.","narration":"San Diego courtroom. My lawyer stood up to call Gary Webb and present the evidence. The judge cut him off — she would not allow any witness or any document about the CIA and drug trafficking. She called it a conspiracy theory. One more word, she said, and it's contempt. The proof that could free us was sitting right there in a briefcase, and the jury would never be allowed to see it. That's not a trial. That's a railroad.","caption":"The proof was in the room. The jury never saw it. #TheLastGame","tags":["Compton","CIA","Justice","TheLastGame","GaryWebb"],"thumbnail_prompt":"tense courtroom, a judge gavel, a briefcase of documents, bold text RAILROADED"},
{"ord":18,"slug":"crack-law","title":"One Law Punished Crack 100x Harder Than Powder","hook_line":"One law punished crack 100 times harder than powder cocaine.","narration":"Here is the law nobody explains. Powder cocaine — a slap on the wrist. Crack cocaine — mandatory minimums, years gone, no mercy. Same drug. And crack was what flooded poor Black neighborhoods like mine, so the sentences fell almost entirely on us. From a prison cell I watched people finally demonstrate against that law. And for supporting them, they threw me in the hole.","caption":"Same drug. 100x the sentence. #TheLastGame","tags":["Compton","CrackEpidemic","Justice","TheLastGame","History"],"thumbnail_prompt":"scales of justice tilted, crack rock vs powder, bold text 100 TO 1"},
{"ord":19,"slug":"the-pardons","title":"They Pardoned Everyone at the Top. He Got 10 Years.","hook_line":"Every official convicted in the scandal was pardoned. He got 10 years.","narration":"While I sat in a cell, here is what happened to the men at the top. The Secretary of Defense — indicted, then pardoned. The CIA's chief of covert operations — convicted of perjury, pardoned. Two more senior officials — convicted, pardoned. Oliver North — conviction overturned. All wiped clean by one President's pen. Me? Ten years, for a deal the record shows the government helped set up. That is the balance of power.","caption":"Pardons at the top. 10 years at the bottom. #TheLastGame","tags":["CIA","IranContra","Justice","TheLastGame","History"],"thumbnail_prompt":"a presidential pen signing pardons over prison bars, bold text PARDONED"},
{"ord":20,"slug":"mothers-testimony","title":"His Mother Took the Stand: He Is My Baby","hook_line":"His mother took the stand and called a kingpin her baby.","narration":"My mother, in her sixties, took the witness stand. Judge, I know my boy. He is a good boy. He is my baby. We gave him a good education. He played baseball. He has three kids and he is a good father. The judge thanked her, kindly. Then she barred the one piece of evidence that could have proven it. My mother went back to her seat next to my father, her eyes full of tears.","caption":"He is my baby. #TheLastGame #Compton","tags":["Compton","Family","TheLastGame","TrueStory"],"thumbnail_prompt":"older Black mother on a witness stand, tears, warm light, bold text MY BABY"},
{"ord":21,"slug":"the-hole","title":"He Kept Telling the Truth. They Put Him in the Hole.","hook_line":"He kept telling the truth in prison. They put him in the hole for it.","narration":"Three weeks into a ten-year bid, I watched the news break the CIA Inspector General's own report — and watched every major paper line up to bury Gary Webb instead of the story. Then the guards came. People outside were demonstrating against the crack law, and somehow I was the one being marched to solitary. Sitting in that darkness, I made a decision. I would not be broken, and I would not be silent.","caption":"They tried to silence him. It didn't work. #TheLastGame","tags":["CIA","GaryWebb","Justice","TheLastGame"],"thumbnail_prompt":"lone figure in a dark solitary cell, a sliver of light, bold text THE HOLE"},
{"ord":22,"slug":"mark-wahlberg","title":"He Pitched His Life to Mark Wahlberg in an $85M Mansion","hook_line":"A Compton kingpin pitched his life story to Mark Wahlberg in an $85M mansion.","narration":"Penny Marshall saw my footage and picked up the phone to Mark Wahlberg. We met at Mark's eighty-five-million-dollar Beverly Hills home — a kid from Nord Street, sitting in that office. He loved the idea. I showed him my film, shot on an old iPhone with a shattered screen, and we all laughed. That meeting turned into a Netflix deal for a story that started under a Compton bridge.","caption":"Nord Street to an $85M pitch meeting. #TheLastGame","tags":["Compton","Hollywood","TheLastGame","Netflix","MarkWahlberg"],"thumbnail_prompt":"opulent Beverly Hills mansion office, a man pitching, bold text THE PITCH"},
{"ord":23,"slug":"shattered-iphone","title":"He Filmed a Netflix Pitch on a Shattered iPhone","hook_line":"He filmed a Netflix pitch on an iPhone with a shattered screen.","narration":"People asked why I never replaced it — the old iPhone with the cracked, shattered screen. Truth is, I only used it to make calls. But that broken phone is what I filmed everything on: rival gang members laying down their colors to build together. When a Hollywood producer saw that footage, the cracked screen did not matter. The story did. Sometimes the most broken tool captures the realest thing.","caption":"The most broken tool caught the realest thing. #TheLastGame","tags":["Compton","Redemption","TheLastGame","Netflix"],"thumbnail_prompt":"an old iPhone with a shattered screen filming gang members building, poetic, bold text SHATTERED"},
{"ord":24,"slug":"master-p","title":"A Mogul Who Isn't Even From Compton Feeds It Every Year","hook_line":"A rap mogul who isn't even from Compton feeds it every single year.","narration":"One of the most giving people I know is Percy Miller — Master P. Every year, P comes to Compton and Watts with me, passing out food, clothes, and toys to people who need it. He is not even from here. He just shows up. In a story full of people who took from my city, I have to honor the ones who give. One person at a time — that is how you change a place.","caption":"He's not even from here. He just shows up. #MasterP #TheLastGame","tags":["Compton","MasterP","Redemption","TheLastGame"],"thumbnail_prompt":"community giveaway in Compton, food and toys, hopeful golden light, bold text HE SHOWS UP"},
{"ord":25,"slug":"mariah-katrina","title":"A Private Jet Dropped Him Into Hurricane Katrina","hook_line":"A private jet to New Orleans dropped him straight into Hurricane Katrina.","narration":"This new world was surreal. One night I am at a party meeting Mariah Carey, struck by how humble she was. Days later, August 2005, I am flown by private jet to New Orleans — and land right as Hurricane Katrina hits. They rerouted me to New York, to one of Penny's houses. A kid from Compton, moving through a world my neighbors could never have imagined. But I never forgot which one made me.","caption":"Compton to a private jet to Katrina. #TheLastGame","tags":["Compton","Hollywood","TheLastGame","TrueStory"],"thumbnail_prompt":"private jet on a tarmac with a storm on the horizon, bold text KATRINA"}
]$json$) as t(ord int, slug text, title text, hook_line text, narration text, caption text, tags jsonb, thumbnail_prompt text)
on conflict (slug) do nothing;
