-- ============================================================================
-- Loop — owner automations (the "who should I text today" list)
-- ----------------------------------------------------------------------------
-- Not the n8n CRM autopilot in hq/automation-setup.sql, and not the parallel
-- session's posting engine (tlg_segments / render-next / post-next). This is
-- the loyalty side: automations_due builds six lists of members who are due a
-- message, the owner sends them from /center/, and automation_mark records what
-- went out so the same person is not pestered again.
--
-- The six kinds and their re-send windows:
--   welcome       once ever, members who joined in the last 30 days
--   winback       every 30 days, last visit older than the shop's winback days
--   reward_ready  every 14 days, points >= reward_at
--   review        every 60 days, visited in the last 2 days, lifetime >= 2
--   birthday      every 300 days, birthday is today in the shop's timezone
--   reminder      every 12 hours, appointments tomorrow in the shop's timezone
--
-- THE BUG (migration automations_scope_suppression_to_client)
-- Every one of those six checks matched automation_log on code + kind and
-- never on CLIENT, even though automation_mark faithfully writes one. A log row
-- belonging to one shop therefore silenced the same code at every other shop.
--
-- Two ways it bit:
--   · automation_mark accepts whatever codes the caller passes and only checks
--     the PIN of the client named in the call. One shop's owner, with their own
--     valid PIN, could mark another shop's member codes and empty that shop's
--     welcome list permanently. Demonstrated before the fix: demo marked a
--     'test' member and test's welcome list went 1 -> 0.
--   · the reminder rule keys on coalesce(member_code, phone) and a walk-in
--     booking has no member_code. Phones are not unique across shops, so two
--     shops sharing a customer suppressed each other's reminders.
--
-- Scoping the reads to the client fixes both, and makes marking a foreign code
-- harmless — it can only pollute the caller's own log.
--
-- DELIBERATELY NOT DONE: validating codes inside automation_mark against
-- reward_members. The reminder kind legitimately passes a PHONE rather than a
-- member code, so a strict lookup there would break reminders for walk-ins.
--
-- ALSO FIXED: booking_set_status writes 'noshow', but the reminder filter
-- excluded 'no-show' with a hyphen, so a no-show appointment was still queued
-- for a reminder. Both spellings are excluded now in case any historical row
-- used the hyphen.
--
-- STILL UNREVIEWED: the send_owner_daily / send_owner_digest / send_test_sms
-- group — dormant until Twilio and Resend keys exist.
-- ============================================================================

create table if not exists public.automation_log(
  id     bigint generated by default as identity primary key,
  at     timestamptz default now(),
  client text,
  code   text,   -- a member code, or a PHONE for the reminder kind
  kind   text
);
create index if not exists automation_log_lookup_idx on public.automation_log(client, code, kind, at desc);

-- ----------------------------------------------------------------------------
-- The writer. Records what the owner actually sent.
-- ----------------------------------------------------------------------------
create or replace function public.automation_mark(p_client text, p_pin text, p_kind text, p_codes jsonb)
returns jsonb language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare s public.reward_settings; c text; n int:=0;
begin
  select * into s from public.reward_settings where client=lower(coalesce(p_client,''));
  if not found then return jsonb_build_object('ok',false,'error','No program.'); end if;
  perform public.pin_gate(p_client, p_pin, s.pin);
  if coalesce(s.pin,'')='' or coalesce(p_pin,'')<>s.pin then return jsonb_build_object('ok',false,'error','Wrong PIN.'); end if;
  for c in select jsonb_array_elements_text(coalesce(p_codes,'[]'::jsonb)) loop
    if coalesce(c,'')<>'' then insert into public.automation_log(client,code,kind) values (lower(p_client),c,p_kind); n:=n+1; end if;
  end loop;
  return jsonb_build_object('ok',true,'marked',n);
end $$;

grant execute on function public.automation_mark(text,text,text,jsonb) to anon, authenticated;

-- ----------------------------------------------------------------------------
-- The reader's fix, kept as the migration rather than a copy of the whole
-- 60-line function: it is surgical, self-verifying and re-runnable, and a
-- hand-transcribed copy of that function would only drift. Run it again after
-- ever rewriting automations_due — it no-ops if the scoping is already there.
-- ----------------------------------------------------------------------------
do $mig$
declare def text; src_before text; src_after text; n_code int; n_scoped int; o oid;
begin
  select p.oid into o from pg_proc p join pg_namespace n on n.oid=p.pronamespace
   where n.nspname='public' and p.proname='automations_due';
  if o is null then raise notice 'automations_due not present'; return; end if;
  select prosrc into src_before from pg_proc where oid=o;

  n_code := (select count(*) from regexp_matches(src_before, 'l\.code=', 'g'));
  if n_code <> 6 then
    raise exception 'ABORT: expected 6 suppression checks, found %', n_code;
  end if;
  if src_before ~ 'l\.client=lower\(p_client\)' then
    raise notice 'already scoped'; return;
  end if;

  def := pg_get_functiondef(o);
  def := replace(def, 'l.code=', 'l.client=lower(p_client) and l.code=');
  def := replace(def,
    'coalesce(lower(status),'''') not in (''cancelled'',''done'',''no-show'')',
    'coalesce(lower(status),'''') not in (''cancelled'',''done'',''noshow'',''no-show'')');
  execute def;

  select prosrc into src_after from pg_proc where oid=o;
  n_scoped := (select count(*) from regexp_matches(src_after, 'l\.client=lower\(p_client\) and l\.code=', 'g'));
  if n_scoped <> 6 then raise exception 'ABORT: scoped % of 6 checks', n_scoped; end if;
  if src_after !~ '''noshow'',''no-show''' then raise exception 'ABORT: status literal not corrected'; end if;
  -- nothing else may have moved
  if replace(replace(src_after, 'l.client=lower(p_client) and l.code=', 'l.code='),
             '''cancelled'',''done'',''noshow'',''no-show''', '''cancelled'',''done'',''no-show''') <> src_before then
    raise exception 'ABORT: changed beyond the two intended edits';
  end if;
end $mig$;

-- ----------------------------------------------------------------------------
-- SECOND FIX (migration automations_deep_merge_saved_config).
--
-- automations_due layered the shop's saved config over the defaults with a
-- plain `def || s.automations`, which is a SHALLOW top-level merge: whatever a
-- shop stored for a kind REPLACED that kind's whole default object instead of
-- layering onto it. Save {"welcome":{"on":false}} and the welcome message text
-- is gone — demonstrated, the template came back empty.
--
-- /center/ does not trigger this: saveAutoCfg() always writes complete
-- {on,template} objects for all six kinds (plus days for winback), and that
-- round-trip was verified clean before and after. The reason to fix it anyway
-- is second-order — any field added to a kind's defaults later would be
-- permanently invisible to every shop that had already saved a config, because
-- their stored object shadows the entire default. That is close to
-- undiagnosable once shops exist.
--
-- Each kind is now merged individually onto its default, so a partial save only
-- overrides the keys it names. Also hardens two garbage cases: a non-object
-- automations value (an array or scalar would otherwise CONCATENATE with the
-- defaults into an array and silently blank every template), and a non-object
-- value for a single kind, which is skipped rather than corrupting that kind.
--
-- Re-runnable: no-ops if the deep merge is already in place.
-- ----------------------------------------------------------------------------
do $mig$
declare def text; src_before text; src_after text; o oid; n int;
  old_line text := 'cfg := def || coalesce(s.automations,''{}''::jsonb);';
  new_block text;
begin
  select p.oid into o from pg_proc p join pg_namespace n2 on n2.oid=p.pronamespace
   where n2.nspname='public' and p.proname='automations_due';
  if o is null then raise notice 'automations_due not present'; return; end if;
  select prosrc into src_before from pg_proc where oid=o;

  if src_before ~ 'jsonb_each\(s\.automations\)' then raise notice 'already deep-merged'; return; end if;

  n := (select count(*) from regexp_matches(src_before, 'cfg := def \|\| coalesce\(s\.automations', 'g'));
  if n <> 1 then raise exception 'ABORT: expected 1 merge line, found %', n; end if;

  new_block :=
    'cfg := def;' || chr(10) ||
    '  if jsonb_typeof(coalesce(s.automations,''null''::jsonb)) = ''object'' then' || chr(10) ||
    '    select def || coalesce(jsonb_object_agg(e.k, coalesce(def->e.k,''{}''::jsonb) || e.v), ''{}''::jsonb)' || chr(10) ||
    '      into cfg from jsonb_each(s.automations) as e(k,v) where jsonb_typeof(e.v) = ''object'';' || chr(10) ||
    '  end if;';

  def := pg_get_functiondef(o);
  def := replace(def, old_line, new_block);
  execute def;

  select prosrc into src_after from pg_proc where oid=o;
  if src_after !~ 'jsonb_each\(s\.automations\)' then raise exception 'ABORT: merge not applied'; end if;
  if replace(src_after, new_block, old_line) <> src_before then
    raise exception 'ABORT: changed beyond the intended merge line';
  end if;
end $mig$;

-- automations_set is a plain store — it validates the PIN and writes p_config
-- verbatim (coalescing to the existing value when null). No shape validation,
-- which is fine now that the reader merges defensively.
create or replace function public.automations_set(p_client text, p_pin text, p_config jsonb)
returns jsonb language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare s public.reward_settings;
begin
  select * into s from public.reward_settings where client=lower(coalesce(p_client,''));
  if not found then return jsonb_build_object('ok',false,'error','No program.'); end if;
  perform public.pin_gate(p_client, p_pin, s.pin);
  if coalesce(s.pin,'')='' or coalesce(p_pin,'')<>s.pin then return jsonb_build_object('ok',false,'error','Wrong PIN.'); end if;
  update public.reward_settings set automations = coalesce(p_config, automations) where client=lower(p_client);
  return jsonb_build_object('ok',true);
end $$;

grant execute on function public.automations_set(text,text,jsonb) to anon, authenticated;
