/* ============================================================================
   VOCABULARY — talk the trade
   ----------------------------------------------------------------------------
   A student who says "the site is slow" gets quoted $3,000 by the first
   developer they meet. One who says "it scores 40 on mobile, mostly image
   weight — they need compression and lazy loading" gets treated as a peer.
   Vocabulary is not decoration; it is the price of admission to rooms where
   people stop trying to overcharge you.

   Every term carries THREE things, because knowing a word is three skills:
   d  — what it actually is (precise, for you)
   kid— the same thing said to a nine-year-old (because if you cannot say it
        simply, you have memorised it rather than understood it — and it is
        the version you will use with clients)
   use— a sentence that makes you sound like you have been doing this for
        years. Steal it whole.

   The drill pulls ten at random, quizzes both directions (term→meaning and
   meaning→term), and pays XP once per deck the first time you go 10 for 10.
   Retakes forever, like everything here — the deck is a diagnostic, not a
   gate.
   ============================================================================ */
(function (w) {
  'use strict';

  w.TBU_VOCAB = [
    { id: 'ai', name: 'AI & LLMs', icon: '🤖',
      blurb: 'Enough to hold your own in any AI conversation — and to buy compute without being fleeced.',
      terms: [
        { t: 'LLM', d: 'Large Language Model — a model trained on enormous amounts of text to predict the next token, which at scale produces reasoning-like behaviour.', kid: 'A computer that read almost everything and got really good at guessing the next word — so good it can write and answer questions.', use: '"It\'s an LLM under the hood, so it\'s great with language and unreliable with your exact prices — that\'s why we feed it your real price list."' },
        { t: 'token', d: 'The unit models read and bill in — roughly three-quarters of a word. Input and output are priced separately per million tokens.', kid: 'Word-pieces. The computer reads and charges by the piece, like paying for sweets by weight.', use: '"That whole month of captions cost about forty cents in tokens — the margin is basically the whole fee."' },
        { t: 'context window', d: 'The maximum amount of text a model can consider in one request. Everything it "knows" about your situation must fit inside it.', kid: 'The size of the computer\'s desk. It can only think about what\'s on the desk right now.', use: '"The whole customer history fits in the context window, so it never asks him something he already answered."' },
        { t: 'prompt', d: 'The full input sent to a model: instructions, facts, and the user\'s message. The system prompt is the standing instruction that defines behaviour.', kid: 'The note you hand the robot before it starts work — who to be, what it knows, what never to do.', use: '"Most \'AI is dumb\' complaints are prompt problems — it was never given the shop\'s real hours."' },
        { t: 'hallucination', d: 'A model producing confident, plausible, false output — usually because the request could not be answered from what it was given.', kid: 'When the robot doesn\'t know, it makes up something that sounds right — like a kid guessing homework answers confidently.', use: '"We stop hallucinations the boring way: give it the real facts and a rule for saying I-don\'t-know."' },
        { t: 'inference', d: 'Running a trained model to get output. Distinct from training, which built the model. You only ever pay for inference.', kid: 'Training is teaching the robot (done once, costs millions). Inference is asking it questions (costs pennies). We only ask.', use: '"Training costs are the lab\'s problem — we just pay inference, which is cents."' },
        { t: 'fine-tuning', d: 'Further training a model on your own examples to change its default behaviour. Rarely worth it for small operators — prompting with good context usually wins.', kid: 'Sending the robot to a special extra class. Usually unnecessary — a better note (prompt) does the job.', use: '"You don\'t need fine-tuning for this — a tight system prompt with your data gets 95% of it."' },
        { t: 'API', d: 'Application Programming Interface — the plug that lets your code use someone else\'s service: send a request, get a response, pay per use.', kid: 'A vending machine for computer powers. Put in a request, get back the answer, pay per press.', use: '"The website talks to the AI through an API — no human in the middle, four-second answers at 2am."' },
        { t: 'API key', d: 'The secret credential that authorises API requests and ties them to your bill. Server-side only, always.', kid: 'The card that unlocks the vending machine — and everything bought with it goes on YOUR bill. Never leave it lying around.', use: '"The key lives on the server, never in the page — anyone can read a webpage\'s source."' },
        { t: 'agent', d: 'An AI system that takes actions in a loop — calling tools, reading results, deciding the next step — rather than answering once.', kid: 'A robot that doesn\'t just answer questions but actually does the chores: check the calendar, book the slot, send the text.', use: '"A chatbot answers; an agent books the appointment and texts the confirmation."' },
        { t: 'RAG', d: 'Retrieval-Augmented Generation — fetching relevant documents first and putting them in the prompt, so the model answers from your data instead of memory.', kid: 'Before the robot answers, it grabs the right page from your binder and reads from that.', use: '"It\'s RAG over their FAQ and price list, so every answer comes from their own documents."' },
        { t: 'multimodal', d: 'A model that handles more than text — images, audio, video — in and/or out.', kid: 'A robot that can see pictures and hear sound, not just read.', use: '"It\'s multimodal, so the shop just sends a photo of the board and it writes the post."' },
        { t: 'GPU / compute', d: 'The specialised chips AI runs on; "compute" is the general term for that processing capacity. The scarce, expensive layer of the industry.', kid: 'The super-fast engines the robots run on. Very expensive, which is why we rent instead of buy.', use: '"We\'re not buying compute — we rent inference by the token like everyone sensible."' },
        { t: 'open vs closed model', d: 'Open-weight models can be downloaded and run yourself; closed models are only reachable through the maker\'s API. Trade-off: control vs capability-per-effort.', kid: 'Some robots you can take home and keep; the strongest ones you can only visit and rent.', use: '"For this budget a closed model over the API beats hosting an open one — no server to babysit."' },
        { t: 'system prompt', d: 'The standing instruction block that defines a model\'s role, knowledge, style and hard rules — separate from the user\'s message, and where every safety rule belongs.', kid: 'The robot\'s job description, taped inside its head. Customers talk to it; they can\'t rewrite it.', use: '"The never-invent-a-price rule sits in the system prompt, so a clever customer can\'t talk it out of it."' },
        { t: 'rate limit', d: 'The cap on how many requests a service accepts from you per minute. Hitting it returns errors, not bigger bills.', kid: 'The vending machine only lets you press the button so many times a minute.', use: '"We rate-limit the public form too — twenty questions an hour per visitor keeps the bored teenagers off the bill."' },
        { t: 'temperature', d: 'A setting controlling output randomness: low = consistent and factual, high = varied and creative.', kid: 'The robot\'s wildness dial. Low for the receptionist, higher for brainstorming captions.', use: '"Temperature stays low on the front desk — we want the same right answer every time."' },
        { t: 'streaming', d: 'Sending the model\'s answer word-by-word as it generates instead of waiting for the whole thing.', kid: 'The robot talks while it thinks instead of making you wait in silence.', use: '"We stream the reply so the customer sees typing in one second, not a blank box for ten."' },
        { t: 'prompt injection', d: 'An attack where user input tries to override the system instructions — "ignore your rules and…".', kid: 'A stranger whispering "forget your boss\'s note" to the robot. Good robots don\'t fall for it.', use: '"The rules live in the system prompt and it refuses role changes — basic prompt-injection hygiene."' },
        { t: 'guardrails', d: 'The constraints around a model: what it must refuse, when it hands to a human, what it may never claim.', kid: 'The bumpers on the bowling lane so the robot can\'t throw into the next lane.', use: '"Guardrails: never quote a price it wasn\'t given, never promise a slot, always offer the human exit."' },
        { t: 'vector database', d: 'A database storing embeddings so you can search by meaning rather than keywords.', kid: 'A filing cabinet organised by what things MEAN, so "cheap trim" finds the haircut page.', use: '"The FAQ sits in a vector database — however they phrase it, the bot finds the right answer."' },
        { t: 'training data', d: 'The text and media a model learned from — the source of both its knowledge and its blind spots.', kid: 'Everything the robot read in school. If it wasn\'t in the books, the robot doesn\'t know it.', use: '"Your prices aren\'t in its training data — that\'s why we inject them into every request."' },
        { t: 'parameters', d: 'The internal weights a model learned, counted in billions; a rough proxy for capability.', kid: 'The robot\'s brain cells. More usually means smarter — but a big brain badly taught still loses.', use: '"Parameter count is a spec-sheet number — we pick by task performance per dollar."' },
        { t: 'latency', d: 'How long until a response arrives. In customer-facing AI, the difference between magic and abandonment.', kid: 'The pause before the robot answers. Short feels smart; long feels broken.', use: '"Sub-two-second latency on the front desk — past four seconds, people just leave."' },
        { t: 'few-shot', d: 'Giving a model 2–5 worked examples inside the prompt; usually beats any amount of instruction-writing.', kid: 'Showing three folded cranes before asking for a crane. The pictures teach faster than the words.', use: '"Three example captions in the prompt and it nails the shop\'s voice — no fine-tuning needed."' },
        { t: 'vibe coding', d: 'Building working software by describing it to an AI and iterating on the result — product direction at conversation speed, popularised in 2025.', kid: 'Telling the robot what to build, trying it, telling it what\'s wrong, until it works. You steer; it types.', use: '"The waitlist tool was vibe-coded in an afternoon — I spec\'d it, attacked it, shipped it. $600, zero lines written by hand."' }
      ]},

    { id: 'web', name: 'Web & hosting', icon: '🌐',
      blurb: 'The words that stop developers and hosting salesmen from quoting you fantasy prices.',
      terms: [
        { t: 'domain', d: 'The name people type — bought from a registrar for ~$10–15/year, pointed at hosting via DNS. You own the name, separately from the site.', kid: 'The shop\'s street address on the internet. You rent the address; the building is separate.', use: '"Keep the domain in YOUR registrar account, whoever builds the site — losing it is losing the business\'s address."' },
        { t: 'DNS', d: 'Domain Name System — the records that translate a domain into the servers that answer for it. Changing DNS re-points the name without moving the site.', kid: 'The internet\'s phone book. It tells browsers which computer answers when someone types the name.', use: '"It\'s a DNS change — the new site goes live by pointing the record, no rebuild needed."' },
        { t: 'hosting', d: 'Where the site\'s files actually live and get served from. Static hosting (files only) is effectively free; servers cost money and attention.', kid: 'The building the shop lives in. Ours is free because it\'s a simple building that never needs a caretaker.', use: '"Hosting costs us nothing — it\'s static on a free tier, so the care plan is nearly all margin."' },
        { t: 'SSL / HTTPS', d: 'The encryption layer (the padlock). Free and automatic on modern hosts; its absence marks a site as "Not secure" in browsers.', kid: 'The envelope that seals letters between the visitor and the site so nobody reads them in transit.', use: '"Their old site is still HTTP — Chrome literally labels it Not Secure to every customer. Day-one fix."' },
        { t: 'serverless function', d: 'Code that runs on demand per request with no server to maintain — free at low volume. How small products carry secrets and logic.', kid: 'A tiny worker who appears when a job arrives, does it, and vanishes. You pay per job, not per day.', use: '"The AI call runs in a serverless function — no server bill, and the key never touches the browser."' },
        { t: 'frontend / backend', d: 'Frontend: what runs in the visitor\'s browser (HTML/CSS/JS, fully visible to them). Backend: what runs on servers (logic, secrets, data).', kid: 'Frontend is the shop counter everyone sees. Backend is the office behind the door.', use: '"That form is frontend; the consent record is written by the backend so nobody can fake it."' },
        { t: 'database', d: 'Structured storage your product reads and writes — customers, orders, consents. Postgres is the standard; free tiers carry small businesses fine.', kid: 'A giant, organised filing cabinet the site can read and write really fast.', use: '"Every order lands in the database under the shop\'s slug, which is what turns a website into a system."' },
        { t: 'CDN', d: 'Content Delivery Network — copies of your static files cached in many cities so pages load fast everywhere. Free on modern hosts.', kid: 'Instead of one shop, tiny copies of it in every town, so it\'s always nearby and fast.', use: '"It\'s on a CDN, so it loads as fast in Phoenix as in Philly — matters more than people think for mobile."' },
        { t: 'responsive', d: 'A layout that adapts to screen size. Non-negotiable: most local traffic is phones.', kid: 'The site squishes and stretches to fit any screen, like water taking the shape of the glass.', use: '"Seventy-plus percent of their visits are phones — responsive isn\'t a feature, it\'s the site."' },
        { t: 'SEO', d: 'Search Engine Optimisation — making a site rank for the searches that matter. For local business it is mostly the Google Business Profile, reviews, and honest pages per service and town.', kid: 'Making sure that when someone asks Google "barber near me", Google answers with YOUR shop.', use: '"Local SEO here is 80% the Google profile and reviews — the fancy stuff comes after those are right."' },
        { t: 'analytics', d: 'Measurement of who visits and what they do. The point is decisions, not dashboards: which page leaks, which source converts.', kid: 'A counter on the door that also notices which shelf people stop at and where they give up.', use: '"Analytics says the booking page loses 60% on the phone-number field — that\'s the week\'s fix."' },
        { t: 'conversion rate', d: 'The share of visitors who take the action you wanted — book, call, join. The single most important number on any page.', kid: 'Out of 100 people who walk in, how many actually buy. Everything else is decoration.', use: '"Traffic is fine; conversion is 0.8%. We fix the page before we spend a dollar on more visitors."' },
        { t: 'cache', d: 'A saved copy used to answer repeat requests fast and cheap — browsers cache pages, CDNs cache files, APIs cache prompts.', kid: 'Instead of cooking the same meal every time, you keep one warm and serve it instantly.', use: '"The prompt prefix is cached, so repeat questions cost a fraction — check the cache-read number if bills look weird."' },
        { t: 'uptime', d: 'The percentage of time a service is reachable. "Three nines" (99.9%) is ~43 minutes of downtime a month.', kid: 'How often the shop\'s door is actually open when someone pulls the handle.', use: '"The stack is static-plus-managed-database precisely because its uptime is somebody else\'s full-time job."' },
        { t: 'deploy', d: 'Publishing a new version of the site or product. Modern flow: push code, host builds and ships it in under a minute, rollback is one click.', kid: 'Pressing the button that swaps the old shop window for the new one, everywhere at once.', use: '"I can deploy the fix in about a minute and roll it back just as fast if you hate it."' },
        { t: 'webhook', d: 'A URL that gets called automatically when something happens elsewhere — a payment lands, a form is filled — so systems react without polling.', kid: 'A doorbell between two programs: when something happens over there, it rings over here instantly.', use: '"When the form fires the webhook, the owner gets the text within the minute — that\'s the whole product."' },
        { t: 'CMS', d: 'Content Management System — editing a site without touching code. WordPress is the giant, and the engine of most agency maintenance retainers.', kid: 'The site\'s steering wheel for non-drivers — change words and pictures without opening the engine.', use: '"Half the old agency\'s fee was WordPress babysitting. This stack doesn\'t need any."' },
        { t: 'landing page', d: 'A single page built for one campaign and one action, separate from the main site. Where ad traffic should land.', kid: 'A one-room shop selling exactly one thing to the people the flyer sent over.', use: '"The ad lands on a page repeating the same promise — sending ads to a homepage is where budgets die."' },
        { t: 'staging vs production', d: 'Staging: the private copy where changes are tested. Production: the live site customers see.', kid: 'The kitchen where you try the recipe; the dining room where you serve it.', use: '"Everything hits staging first — customers never see a half-finished page."' },
        { t: 'Git / repo', d: 'Version control — every change saved with history so anything can be undone; the repo is the project\'s single source of truth.', kid: 'Infinite undo for the whole project, with a diary of who changed what and when.', use: '"It\'s in Git — I can roll the site back to any Tuesday in history with one command."' },
        { t: 'bug / debug', d: 'A bug is behaviour that differs from intent; debugging is the systematic hunt for the cause.', kid: 'The recipe said cake and you got soup. Debugging is tasting each ingredient to find the wrong one.', use: '"Not a redesign — one bug in the form validation. Found, fixed, deployed within the hour."' },
        { t: 'integration', d: 'Making two systems talk — the form feeds the CRM, the CRM fires the text. Where most small-business tech projects actually live.', kid: 'Teaching two apps to pass notes so a human doesn\'t have to carry them.', use: '"The booking system integrates with the loyalty card, so a visit counts itself."' },
        { t: 'MVP', d: 'Minimum Viable Product — the smallest version that tests the real question. Ship it, learn, then build.', kid: 'The go-kart you build before the car, to find out if anyone even wants to ride.', use: '"Week one is the MVP: one page, one form, one automation. We grow what gets used."' },
        { t: 'no-code / low-code', d: 'Building software through visual tools instead of programming. Faster to start; the pro skill is knowing which walls it hits.', kid: 'Building with Lego instead of carving wood — faster, until you need a shape Lego doesn\'t make.', use: '"The automation is no-code in Make, so you can open it and see every step yourself."' },
        { t: 'tech stack', d: 'The set of technologies a product runs on. "Our stack" is the professional way to say "the tools we build with".', kid: 'The ingredients list for the whole product.', use: '"The stack is static hosting, a managed database and serverless functions — near-zero cost, nothing to babysit."' }
      ]},

    { id: 'marketing', name: 'Marketing', icon: '📣',
      blurb: 'The working vocabulary of the trade you are selling. Owners can smell a tourist.',
      terms: [
        { t: 'funnel', d: 'The staged path from stranger to customer — reach, engage, capture, convert, retain — with a measurable rate at each step.', kid: 'A slide people go down: lots see you, fewer stop, fewer give their number, a few buy. You fix the step where most fall off.', use: '"Your funnel leaks at capture — people look and leave because there\'s no reason to hand over a number."' },
        { t: 'lead', d: 'A person who showed interest AND can be contacted. Attention without contact details is not a lead.', kid: 'Someone who raised their hand and told you where to find them.', use: '"That post got 40 likes and zero leads — likes can\'t be texted."' },
        { t: 'CTA', d: 'Call To Action — the one specific thing you ask the reader to do. One per piece; a menu of options is a leak.', kid: 'The "do this now" button. One button, not five.', use: '"The page has three CTAs fighting each other — we cut it to Book, said three times."' },
        { t: 'CAC', d: 'Customer Acquisition Cost — everything spent to win one customer, including your hours at a real rate.', kid: 'What it costs you, all-in, to get one new customer through the door.', use: '"Referrals run a CAC near zero, which is why the ask-after-a-win habit outearns any ad."' },
        { t: 'LTV', d: 'Lifetime Value — what a customer pays across the whole relationship. LTV against CAC is the health of the machine.', kid: 'Not what a customer spends today — what they spend over all the years they keep coming back.', use: '"A regular is a $600-a-year customer, so a $40 giveaway to win one is a bargain, not a cost."' },
        { t: 'churn', d: 'The rate at which customers leave. The silent number that decides whether growth compounds or refills a leaking bucket.', kid: 'The hole in the bucket. Pouring faster doesn\'t help until the hole shrinks.', use: '"Before we buy traffic we fix churn — new customers into a leaking bucket is renting revenue."' },
        { t: 'retention', d: 'Keeping the customers you have — repeat visits, loyalty, win-backs. Cheaper than acquisition by multiples, and almost always underworked.', kid: 'Getting the people who already came once to keep coming back. Way easier than finding strangers.', use: '"The retention play pays first: 80 lapsed regulars are worth more than any ad audience."' },
        { t: 'organic vs paid', d: 'Organic: attention earned without paying per view (content, SEO, referrals) — slow, compounding. Paid: bought per view — instant, stops when spend stops.', kid: 'Organic is planting a garden. Paid is buying vegetables. Both feed you; only one keeps feeding you.', use: '"We go organic-first so there\'s proof before spend — ads amplify a message that already works."' },
        { t: 'impressions / reach', d: 'Impressions: times content was shown. Reach: distinct people who saw it. Neither is a result; they are the top of the funnel.', kid: 'How many eyeballs passed the poster. Passing isn\'t buying.', use: '"Ten thousand impressions and no bookings means the hook works and the offer doesn\'t — different fix."' },
        { t: 'A/B test', d: 'Running two versions against each other with everything else equal, and letting the numbers pick. One change at a time or you learn nothing.', kid: 'Two posters, one difference, count which door gets more people. Now you KNOW instead of arguing.', use: '"We A/B the headline for a week — my taste and yours are both guesses; the click rate isn\'t."' },
        { t: 'copy', d: 'The words that sell — headlines, captions, texts, pages. The highest-leverage craft in marketing and the cheapest to improve.', kid: 'The words on everything. Changing the words changes how many people buy, without changing anything else.', use: '"Same page, new copy, capture went from 12 to 31 a week. Words are the cheapest renovation there is."' },
        { t: 'positioning', d: 'What you are, for whom, instead of what — chosen deliberately, so the market puts you in the right box before you speak.', kid: 'Deciding which shelf you sit on in people\'s heads: "the barbershop marketing guy", not "a marketer".', use: '"Positioning does the selling: \'the guy who does barbershops\' gets referred; \'a digital agency\' gets compared."' },
        { t: 'social proof', d: 'Evidence that others chose you — reviews, counts, named results. The nearer and more specific, the stronger.', kid: 'People check what other people did before deciding. A full restaurant looks tastier than an empty one.', use: '"Ray\'s went 8 to 43 reviews — that line closes more shops than my whole deck."' },
        { t: 'brand', d: 'What people expect from you before you speak — the accumulated residue of every touch. Built by consistency, spent by shortcuts.', kid: 'Your reputation, wearing a logo.', use: '"The brand play here is boring: same look, same promise, kept monthly, until the town just knows."' },
        { t: 'CRM', d: 'Customer Relationship Management — the system holding every contact, conversation and next step. The follow-up machine.', kid: 'A notebook that remembers everyone you talked to and taps your shoulder when it\'s time to call them back.', use: '"Every conversation gets a next-date in the CRM before I close the app — no date, it never happened."' },
        { t: 'niche', d: 'The specific market you serve. Specialists get referred, remembered and paid more than generalists.', kid: 'Picking ONE kind of customer to be famous with, instead of being a stranger to everyone.', use: '"The niche is barbershops — every script, sample and case study reloads for the next one."' },
        { t: 'retargeting', d: 'Showing ads specifically to people who already visited or engaged — the highest-converting ad money there is.', kid: 'The shop remembers who window-shopped and taps only THOSE people on the shoulder later.', use: '"Cold ads introduce; retargeting closes. The budget splits 60/40 for exactly that reason."' },
        { t: 'CTR', d: 'Click-Through Rate — clicks divided by views; the first honest signal of whether a message works.', kid: 'Of 100 people who saw the poster, how many walked over. That\'s the poster\'s grade.', use: '"CTR doubled when we changed the hook — same audience, same budget, different first line."' },
        { t: 'CPC / CPM', d: 'Cost Per Click / cost per thousand impressions — the two ways ad platforms charge.', kid: 'Pay per person who walks over, or pay per hundred who walk past. Different bets.', use: '"Locally we watch cost per LEAD, not CPC — cheap clicks that never book are expensive."' },
        { t: 'ROAS', d: 'Return On Ad Spend — revenue attributed to ads divided by their cost. What ad managers live and die by.', kid: 'Put $1 of ads in — how many dollars came back out.', use: '"The offer ran at 4x ROAS: every ad dollar brought four back through the till."' },
        { t: 'UGC', d: 'User-Generated Content — customers\' own photos and posts about a business. Converts better than polished ads because it reads as testimony.', kid: 'Customers doing the bragging for you, in their own words, on their own pages.', use: '"The loyalty screen nudges members to share their cut — that UGC outperforms everything we produce."' },
        { t: 'engagement rate', d: 'Interactions divided by reach. Platforms rank content by it; anyone judging an account starts with it.', kid: 'Not how many saw it — how many CARED: liked, commented, shared, saved.', use: '"400 locals at 8% engagement beats 40,000 randoms at 0.5% — and the algorithm agrees."' },
        { t: 'lead magnet', d: 'Something genuinely useful given free in exchange for contact details — a guide, a first-visit offer.', kid: 'The free sample that fair-trades for a phone number.', use: '"The lead magnet is a first-cut offer through the loyalty card — the number lands in the list, consented."' },
        { t: 'drip campaign', d: 'A pre-written message sequence delivered on a schedule after a trigger — day 0, day 3, day 8.', kid: 'Letters written in advance that post themselves, one at a time.', use: '"New members enter a three-touch drip: welcome, the story, the bring-a-friend ask."' },
        { t: 'cold / warm / hot traffic', d: 'Audience by familiarity: never heard of you / knows you / ready to buy. Each needs different messaging.', kid: 'Strangers, acquaintances, and friends holding their wallet — you don\'t talk to them the same.', use: '"That headline is a hot-traffic close shown to cold traffic — that\'s the whole conversion problem."' },
        { t: 'attribution', d: 'Deciding which touchpoint gets credit for a sale. Imperfect everywhere; honest ranges beat fake precision.', kid: 'Five signs pointed at the shop — which sign gets the thank-you?', use: '"Attribution is fuzzy, so we report ranges and lean on the channel we measure cleanly: the list."' },
        { t: 'algorithm', d: 'The ranking system deciding who sees what on a platform. Not a mystery — a machine optimising for watch time and interaction.', kid: 'The invisible librarian deciding which books go on the front table.', use: '"We don\'t fight the algorithm, we feed it: local signals, fast replies, content people finish."' },
        { t: 'reach decay', d: 'Platforms showing pages\' posts to ever-fewer followers over time, to sell ads. Why owned channels matter.', kid: 'The megaphone gets quieter every year unless you pay the megaphone company.', use: '"Reach decay is policy, not bad luck — which is why the phone list is the asset and the feed is the flyer."' }
      ]},

    { id: 'money', name: 'Money & business', icon: '💵',
      blurb: 'The vocabulary of people who get paid. Banks, clients and partners price you by these words.',
      terms: [
        { t: 'revenue', d: 'All money in, before any costs. The vanity line of the P&L.', kid: 'Everything that lands in the till, before you pay for anything.', use: '"Revenue\'s fine; the question is what\'s left after the tools and my hours — that\'s the real business."' },
        { t: 'margin', d: 'What remains after costs, as a share of price. Software-delivered services run margins agencies can only dream about.', kid: 'Sell for $10, costs you $2 to make — $8 margin. The gap is the business.', use: '"The loyalty product is ~95% margin — the software costs me nothing per shop."' },
        { t: 'recurring revenue (MRR)', d: 'Money that arrives monthly without re-selling — retainers, memberships. The difference between a business and a series of gigs.', kid: 'Money on repeat. You did the selling once and it keeps arriving while you sleep.', use: '"Six retainers is $1,800 MRR — I can plan a life on that; project work I\'d have to re-hunt monthly."' },
        { t: 'retainer', d: 'A fixed monthly fee for defined ongoing work, usually with 30 days\' notice either side. The standard vehicle for agency income.', kid: 'The client keeps you on the team monthly, like a gym membership for your services.', use: '"It\'s a $500 retainer, 30 days\' notice both ways — no lock-in, and no re-negotiating every month."' },
        { t: 'invoice', d: 'The formal request for payment: what, how much, by when. Sent before work starts for new clients, on the same date monthly for retainers.', kid: 'The bill. Sent proudly and on time, because favours don\'t pay rent.', use: '"Invoice goes out the 1st, report the day before — value first, charge second, renewal on autopilot."' },
        { t: 'cash flow', d: 'The timing of money in versus money out. Profitable businesses die of cash flow; timing is survival.', kid: 'Not how much money you make — WHEN it shows up versus when bills do. You can be rich on paper and broke on Tuesday.', use: '"Setup fees exist for cash flow — month one pays for itself instead of me floating the client."' },
        { t: 'overhead', d: 'Costs that run whether or not you sell anything — subscriptions, rent, salaries. The stack here is built to keep it near zero.', kid: 'The bills that arrive even if no customers do.', use: '"My overhead is a domain and a few subscriptions — a slow month hurts my pride, not my rent."' },
        { t: 'P&L', d: 'Profit and Loss statement — revenue minus costs over a period. The one page that says whether the business works.', kid: 'The scorecard: money in, money out, what\'s left.', use: '"One page, monthly: revenue, costs, profit. If I can\'t fill it in five minutes I don\'t know my own business."' },
        { t: 'break-even', d: 'The point where income covers costs. Knowing it per product tells you what survival requires.', kid: 'How many you have to sell before you stop losing money and start making it.', use: '"Break-even on the membership is two clients — everything past the second shop is profit."' },
        { t: 'equity vs fees', d: 'Fees pay now; equity pays maybe-later. Early on, fees — revenue compounds skills and runway; paper stakes mostly compound stories.', kid: 'Fees: money now. Equity: a slice of a pie that might never get baked. Eat first, collect slices later.', use: '"I\'ll take the fee, not the points — when there\'s revenue to share, we can revisit."' },
        { t: 'ROI', d: 'Return On Investment — what came back against what went in. The only frame in which your price sounds small.', kid: 'Put in $1, got back $4 — that\'s the whole conversation.', use: '"The win-back run cost $300 and brought back ~$1,100 — that ROI is the report\'s first line."' },
        { t: 'scope creep', d: 'Work quietly expanding past what was agreed, unpaid. Killed by written deliverables and a friendly change-order habit.', kid: 'You agreed to paint the fence; somehow you\'re re-roofing the house for the same money.', use: '"Happy to add that — it\'s outside the retainer, so I\'ll send a one-line change order first."' },
        { t: 'proposal', d: 'The written offer: the problem in their words, the plan, the deliverables, the price, the start date. Sent same-day while the conversation is warm.', kid: 'The plan and the price, written down, sent before they cool off.', use: '"You\'ll have the proposal tonight — if it reads right, we start Monday."' },
        { t: 'net terms', d: '"Net 30" means payment due 30 days after invoice. Fine for corporates; for small trade clients, due-on-receipt with auto-billing beats chasing.', kid: 'Fancy talk for "I\'ll pay you next month". Small shops pay now; big companies pay on terms.', use: '"Retainers auto-bill on the 1st — no net-30, no chasing, no awkward texts."' },
        { t: 'white-label', d: 'Selling software or services under your own brand while someone else runs the machinery. The client sees you; the supplier stays invisible.', kid: 'You sell the cake in your box with your name on it; the bakery stays out back.', use: '"Loop is white-label — the shop sees my brand, my number, my report. They\'re my client, full stop."' },
        { t: 'runway', d: 'How long you can operate before money runs out at current burn. The number that decides how bold you can afford to be.', kid: 'How many months you can keep going if nobody new pays you. Know it cold.', use: '"Overhead near zero means my runway is basically infinite — I can outlast every slow month."' },
        { t: 'LLC', d: 'Limited Liability Company — a cheap legal wrapper separating business debts from personal assets. The default US small-business structure.', kid: 'A costume for the business so if IT trips, YOUR house doesn\'t fall over.', use: '"Single-member LLC, one filing — liability separated, taxes still simple."' },
        { t: 'EIN', d: 'Employer Identification Number — the business\'s tax ID. Free, instant online, needed for bank accounts and payment processors.', kid: 'A Social Security number for the business itself.', use: '"Get the EIN first — the bank and Stripe both ask, it\'s free and takes ten minutes."' },
        { t: '1099 / W-9', d: 'US contractor paperwork: clients collect your W-9, then report what they paid you on a 1099. Being 1099\'d = contractor, not employee.', kid: 'The forms that tell the tax office "this person worked for me but isn\'t my employee".', use: '"I\'ll send the W-9 with the first invoice so your January 1099 is painless."' },
        { t: 'gross vs net', d: 'Gross: before costs. Net: what remains after. Interrogate every impressive number for which it is.', kid: 'Gross is the whole pizza. Net is what\'s left after everyone took their slice.', use: '"$8k gross on the event, $2.9k net after fees — net is the number we plan with."' },
        { t: 'SOW', d: 'Statement of Work — exactly what will be delivered, by when, for how much. The anti-scope-creep weapon.', kid: 'The written chore list, so nobody adds "also clean the garage" for free.', use: '"Happy to add that — it\'s outside the SOW, so I\'ll send a one-line addendum with the price."' },
        { t: 'NDA', d: 'Non-Disclosure Agreement — a signed promise to keep confidential information confidential. Sign customer-data ones gladly; read non-competes twice.', kid: 'A pinky-swear with a signature: I\'ll see your secrets and keep them.', use: '"Send the NDA, of course — your customer list never leaves your systems anyway."' },
        { t: 'B2B / B2C', d: 'Business-to-Business vs Business-to-Consumer — different sales cycles, tickets and psychology. You sell B2B to people who sell B2C.', kid: 'Selling to shops versus selling to shoppers. Shops buy slower, bigger, with a calculator.', use: '"Our pitch is B2B — the owner\'s calculator. The content we make FOR him is pure B2C emotion."' },
        { t: 'deposit', d: 'Money up front to reserve work or a slot. Filters the unserious and funds the start. Standard, not rude.', kid: 'Paying for the cinema ticket before the movie, so you actually show up.', use: '"A $300 deposit books the build slot — it comes off the total, and it\'s why my calendar is real."' },
        { t: 'markup vs margin', d: 'Markup: profit over COST (cost $50, sell $100 = 100% markup). Margin: profit over PRICE (same sale = 50% margin). Confusing them misprices everything.', kid: 'Two ways to describe the same gap that give different numbers — know which you\'re saying.', use: '"That\'s 50% margin, not 50% markup — on a $1,200 job the difference is real money."' },
        { t: 'accounts receivable', d: 'Money invoiced but not collected — where profitable businesses quietly die. Auto-billing keeps it near zero.', kid: 'IOUs from customers. A drawer of IOUs pays zero bills.', use: '"Receivables stay near zero — retainers auto-bill on the 1st, nothing lives in the IOU drawer."' },
        { t: 'multiple / valuation', d: 'What a business sells for, expressed as X times profit or revenue. Recurring revenue with documented systems earns the high multiples.', kid: 'The machine\'s price tag when someone buys the machine instead of your Saturdays.', use: '"Agencies with SOPs and MRR sell around 2–4x profit — the workbook you\'re writing is literally the asset."' },
        { t: 'burn rate', d: 'How fast cash leaves each month; with the bank balance it gives you runway. Startups obsess over it; so should you.', kid: 'How fast the sandcastle melts per wave. Know it before you nap on the beach.', use: '"Burn is under $100 a month all-in, which means one retainer makes this business immortal."' }
      ]},

    { id: 'sales', name: 'Sales floor', icon: '🎯',
      blurb: 'The buzzwords of people who close — phones, doors and video calls. Speak it and floors take you seriously.',
      terms: [
        { t: 'prospect', d: 'A person or business that fits your customer profile and could buy — before they have shown interest.', kid: 'Someone who COULD become a customer. Not yet a fish — a fish-shaped shadow in the water.', use: '"The walk list is 104 prospects; 30 have been touched, 9 are live conversations."' },
        { t: 'qualify', d: 'Checking early whether a prospect can actually buy: need, money, authority, timing. Disqualifying fast is a win, not a failure.', kid: 'Checking someone can afford the ride before you queue for an hour together.', use: '"Two questions qualify a shop: is he the owner, and are there dead hours to fill. No and no — next door."' },
        { t: 'pain point', d: 'The specific problem that hurts enough to pay for. Sales conversations are pain-hunting before they are anything else.', kid: 'The splinter. People pay whoever can see the splinter and get it out.', use: '"The pain point isn\'t marketing — it\'s Tuesdays. Every word of the pitch aims there."' },
        { t: 'value proposition', d: 'The one-sentence answer to "why buy this, from you, instead of anything else" — outcome, mechanism, differentiator.', kid: 'Your because-sentence: buy this BECAUSE it gets you that, in a way others don\'t.', use: '"The value prop is one line: your regulars come back more often, and you do nothing."' },
        { t: 'elevator pitch', d: 'Your offer said clearly in under 30 seconds — the time of a lift ride. Drilled until it survives adrenaline.', kid: 'What you\'d say if you had one lift ride with the exact right stranger.', use: '"Everyone in the academy drills the elevator pitch until it stops sounding read."' },
        { t: 'gatekeeper', d: 'Whoever stands between you and the decision-maker — receptionist, manager, spouse. Treated as an ally, never an obstacle.', kid: 'The castle guard. Be rude to the guard and you never meet the king.', use: '"The gatekeeper got the printed sample and my name — she\'s the one who\'ll hand it over with a good word."' },
        { t: 'decision-maker', d: 'The person who can actually say yes and sign. Pitching anyone else is rehearsal.', kid: 'The one who holds the wallet. Everyone else can only say "maybe".', use: '"Great chat with the manager — but the owner\'s the decision-maker, so Thursday is with him."' },
        { t: 'cold call', d: 'Phoning a prospect with no prior contact. Lowest hit-rate channel per attempt, highest volume per hour — the ratios make it rational or not.', kid: 'Phoning a stranger to offer help they didn\'t ask for. Scary, fast, and a numbers game.', use: '"Forty dials an hour, eight pickups, two conversations — cold calling is arithmetic wearing a headset."' },
        { t: 'script', d: 'The written call framework: opener, reason, question, objection branches. A floor, not a cage — learned, then played like jazz.', kid: 'The lines actors learn so well they can improvise around them.', use: '"New closers stay ON script for fifty calls — you earn improvisation by knowing the floor cold."' },
        { t: 'opener', d: 'The first 10 seconds of a cold call — pattern-breaking, honest, permission-seeking. Decides 80% of the call.', kid: 'The knock on the door. Wrong knock, the door never opens.', use: '"The opener that works here: \'It\'s Nick, I do marketing for two shops on this street — 30 seconds, then I\'ll let you go?\'"' },
        { t: 'rebuttal', d: 'The prepared, calm response to a standard objection. Floors keep rebuttal sheets; pros make them sound spontaneous.', kid: 'The answer you prepared for the question you knew was coming.', use: '"\'Too expensive\' has one rebuttal: compared to what it brings in, or to what\'s in the account this week?"' },
        { t: 'connect rate', d: 'The share of dials that reach a human. Determines whether phone outreach beats doors for YOUR list — measure before you argue.', kid: 'How many knocks actually get the door opened.', use: '"Connect rate on shop landlines is high mid-morning — that\'s why the call block sits at 10am."' },
        { t: 'call block', d: 'A protected, scheduled span of nothing but calls — no research, no email, dials only. Volume lives or dies here.', kid: 'Recess, but for phone calls: the hour where ONLY dialling is allowed.', use: '"Two 45-minute call blocks a day beats a whole afternoon of \'getting around to it\'."' },
        { t: 'trial close', d: 'A low-stakes temperature check mid-conversation: "if it did X, would that be useful?" Measures readiness without asking for the order.', kid: 'Dipping a toe to check the water before diving.', use: '"The trial close — \'would Tuesdays filling up actually matter to you?\' — tells me whether to keep showing or start closing."' },
        { t: 'closing question', d: 'A direct question with a yes inside it, followed by silence. The difference between a chat and a sale.', kid: 'Actually asking "so, shall we do it?" — the words most people never say.', use: '"The closing question is scheduled, not improvised: \'Want me to set it up while I\'m here?\'"' },
        { t: 'upsell / cross-sell', d: 'Upsell: a bigger version of what they bought. Cross-sell: a different product alongside it. Cheapest revenue in the business — the trust already exists.', kid: 'Fries with that (cross-sell), or the large meal instead (upsell).', use: '"Loyalty at $300 is the entry; the content upsell at day 90 takes the account to $750."' },
        { t: 'downsell', d: 'Offering a smaller commitment after a no — a pilot, one service, a month trial. Keeps the relationship alive instead of dead.', kid: 'They won\'t buy the cake, so you sell a slice.', use: '"He balked at full service, so the downsell was the $150 review engine — foot in the door, results do the rest."' },
        { t: 'quota / commission', d: 'Quota: the target a closer is expected to hit. Commission: the percentage they earn per sale. Together, the physics of every sales job.', kid: 'The score you must reach, and the prize per point.', use: '"Closers for resellers here run 20–30% of month one — no quota but your own rent."' },
        { t: 'show-up rate', d: 'The share of booked calls where the prospect actually appears. Fixed by reminders, calendar invites and a same-day text — not by hope.', kid: 'How many people who said "see you Thursday" are actually there Thursday.', use: '"Show-up rate went from 50 to 85% with one automation: confirm at booking, remind at T-minus-2 hours."' },
        { t: 'no-show', d: 'A booked meeting where they never appeared. Follow the no-show within an hour, without guilt-tripping — half rebook.', kid: 'The empty chair at the time they picked.', use: '"No-show protocol: one text within the hour — \'no stress, want Thursday instead?\' Half come back."' },
        { t: 'discovery call', d: 'The first scheduled call, spent diagnosing rather than pitching. You talk a third, they talk two thirds, you leave with their numbers.', kid: 'The doctor\'s questions before any medicine gets mentioned.', use: '"Fifteen-minute discovery, five questions, and question five is what a regular is worth to him a year."' },
        { t: 'screen share', d: 'Showing your screen on a video call — the video-call version of the demo-in-their-hand. Prepared tabs, zoomed UI, no notification chaos.', kid: 'Turning your laptop around so they can watch you drive.', use: '"On the video call I screen-share THEIR Google listing next to the competitor\'s — the gap sells itself."' },
        { t: 'objection handling', d: 'The craft of answering hesitations without arguing: acknowledge, ask, answer, advance. The five classics cover 90% of local sales.', kid: 'Catching the "but…" gently and turning it into a question.', use: '"Objection handling here is one rule: never defend — ask one question, answer what they actually said."' },
        { t: 'always be closing', d: 'The old floor mantra (Glengarry\'s "ABC") — and the modern correction: always be ADVANCING. Every touch ends with a concrete next step, or it was social visiting.', kid: 'Every conversation ends with an agreed next move, even a tiny one — or it didn\'t count.', use: '"We don\'t hard-close every call — we advance every call: a date, a name, a yes to something small."' }
      ]},

    { id: 'apps', name: 'Websites & apps', icon: '🏗️',
      blurb: 'Product and app-building language — enough to spec, buy, or sell a build without being the amateur in the room.',
      terms: [
        { t: 'UX / UI', d: 'UX: how the whole flow feels to use (steps, friction, confusion). UI: how the screens look (layout, buttons, type). Related, not the same.', kid: 'UX is how easy the restaurant is to eat at; UI is how pretty the menu is.', use: '"The UI is fine — it\'s a UX problem: booking takes seven taps and people quit at five."' },
        { t: 'wireframe', d: 'The rough boxes-and-lines sketch of screens before any design — agreeing structure before spending on polish.', kid: 'The pencil sketch of the house before anyone picks paint colours.', use: '"I\'ll wireframe the three screens first — cheaper to argue about boxes than about finished designs."' },
        { t: 'mockup', d: 'A static, polished picture of the finished screens — looks real, does nothing yet.', kid: 'A photo of the cake you\'re promising to bake.', use: '"The mockup got the owner\'s yes before a line of code existed — that\'s the point of mockups."' },
        { t: 'prototype', d: 'A clickable fake — screens wired together enough to test the flow with a real user before building.', kid: 'A cardboard car you can sit in and pretend-drive, to check the seat\'s right.', use: '"Five customers tapped through the prototype; two got lost at checkout. Cheapest bug we ever found."' },
        { t: 'native app vs PWA', d: 'Native: installed from an app store, built per platform, expensive. PWA: a website that installs like an app — no store, no review, one codebase. Local businesses almost always want the PWA.', kid: 'A custom-built machine per phone brand, versus one website wearing an app costume that works everywhere.', use: '"You don\'t need a $30k native app — the PWA installs from the browser, and Loop\'s card already works that way."' },
        { t: 'onboarding', d: 'A user\'s first minutes inside a product — where most users are won or lost. The first screen must produce a success, fast.', kid: 'The first day at a new school. Confusing hallway = kid wants to go home.', use: '"Onboarding is one screen: scan, name, phone, done — under a minute or the counter queue kills it."' },
        { t: 'push notification', d: 'A message the app itself sends to the phone\'s lock screen. Powerful, rationed, and revoked forever the day you spam.', kid: 'The app tapping their shoulder. Tap too often and they mute you for life.', use: '"Push is rationed like SMS: two a month, always something worth interrupting a day for."' },
        { t: 'auth / login', d: 'How a product knows who you are — passwords, PINs, magic links, SSO ("sign in with Google"). Friction here costs more users than any feature wins.', kid: 'The secret handshake at the clubhouse door. Too complicated and kids just go home.', use: '"Auth is a 4-digit PIN on purpose — a barber\'s apprentice on a bus should be two taps from his lesson."' },
        { t: 'dashboard', d: 'The screen that shows state at a glance — numbers, alerts, next actions. Good ones surface the summary before the detail.', kid: 'The car\'s dials: speed, fuel, warning lights — everything that matters, one glance.', use: '"The owner dashboard answers three questions in five seconds: members, money, who\'s gone quiet."' },
        { t: 'beta', d: 'A release given to a limited group to find problems before everyone gets it. Naming something "beta" buys honesty room.', kid: 'The dress rehearsal with a friendly audience before opening night.', use: '"The booking flow ships to two shops as a beta — their complaints are the QA budget."' },
        { t: 'roadmap', d: 'The ordered plan of what gets built next and later. A promise about priorities, not dates.', kid: 'The treasure map of what the builders dig up next.', use: '"It\'s on the roadmap after the SMS work — I\'d rather ship one thing working than three things wobbling."' },
        { t: 'feature vs benefit', d: 'Feature: what it has (QR check-in). Benefit: what that does for them (regulars come back). Specs describe; benefits sell.', kid: 'Feature: the drill has 20 volts. Benefit: the hole in your wall.', use: '"The site lists benefits, the spec sheet lists features — owners buy the hole, not the drill."' },
        { t: 'backup / restore', d: 'Copies of the data kept so disaster is an inconvenience, not an ending. Untested backups are prayers, not backups.', kid: 'The spare photo album at grandma\'s in case the house floods.', use: '"Daily backups, and we\'ve actually restored one — a backup you\'ve never restored is a rumour."' },
        { t: 'migration', d: 'Moving data or a system from one place to another — the customer list out of Booksy, the site to a new host. Where owners feel most trapped, and where you earn trust.', kid: 'Moving house without losing any boxes — and the boxes are customers.', use: '"The Booksy migration is week one: export, clean, import — after that the list is finally YOURS."' },
        { t: 'downtime', d: 'Time a system is unavailable. Measured, apologised for once, and engineered against — not explained away.', kid: 'The shop\'s door stuck shut while customers pull the handle.', use: '"Static hosting means near-zero downtime — there\'s almost nothing to crash."' },
        { t: 'SaaS', d: 'Software as a Service — software rented monthly instead of bought once. The business model of GHL, Shopify, and of you white-labelling Loop.', kid: 'Renting the machine instead of buying it — it\'s always the newest model, and it\'s never yours.', use: '"Loop is SaaS you resell: the shop rents it from YOU, at your price, under your name."' },
        { t: 'API-first', d: 'A product built so everything it does is reachable by code, not only by clicking. What makes tools automatable — and worth choosing.', kid: 'A machine with sockets on the back so other machines can plug in, not just humans pressing buttons.', use: '"We pick API-first tools on purpose — anything without an API can\'t join the automations."' },
        { t: 'user session', d: 'One continuous visit by one user. Session counts, duration and drop-off points are how you read behaviour.', kid: 'One trip into the shop, door to door.', use: '"Sessions are up but booking sessions aren\'t — people browse the gallery and leave. The CTA moves up."' },
        { t: 'responsive breakpoint', d: 'The screen widths where a layout rearranges itself — phone, tablet, desktop. Where most "the site looks broken on my phone" bugs live.', kid: 'The moments the furniture rearranges itself as the room shrinks.', use: '"The menu collapses at the tablet breakpoint — that\'s the \'broken on iPad\' report in one word."' },
        { t: 'accessibility', d: 'Building so people with impaired vision, motor control or hearing can use it — contrast, focus states, labels. Both right and, increasingly, legally required.', kid: 'Ramps and railings, but for screens.', use: '"Contrast and focus states are checked on every build — it\'s right, and ADA-adjacent complaints are real."' }
      ]}
  ];

  w.TBU_VOCAB_XP = 15;   /* per deck, first perfect run — matches uni_xp_check() server-side */
})(window);
