/* ============================================================================
   VOCABULARY — talk the trade
   ----------------------------------------------------------------------------
   A student who says "the site is slow" gets quoted $3,000 by the first
   developer they meet. One who says "it scores 40 on mobile, mostly image
   weight — they need compression and lazy loading" gets treated as a peer.
   Vocabulary is not decoration; it is the price of admission to rooms where
   people stop trying to overcharge you.

   Every term carries THREE things, because knowing a word is three skills:
   d  — what it actually is (precise, for you)
   kid— the same thing said to a nine-year-old (because if you cannot say it
        simply, you have memorised it rather than understood it — and it is
        the version you will use with clients)
   use— a sentence that makes you sound like you have been doing this for
        years. Steal it whole.

   The drill pulls ten at random, quizzes both directions (term→meaning and
   meaning→term), and pays XP once per deck the first time you go 10 for 10.
   Retakes forever, like everything here — the deck is a diagnostic, not a
   gate.
   ============================================================================ */
(function (w) {
  'use strict';

  w.TBU_VOCAB = [
    { id: 'ai', name: 'AI & LLMs', icon: '🤖',
      blurb: 'Enough to hold your own in any AI conversation — and to buy compute without being fleeced.',
      terms: [
        { t: 'LLM', d: 'Large Language Model — a model trained on enormous amounts of text to predict the next token, which at scale produces reasoning-like behaviour.', kid: 'A computer that read almost everything and got really good at guessing the next word — so good it can write and answer questions.', use: '"It\'s an LLM under the hood, so it\'s great with language and unreliable with your exact prices — that\'s why we feed it your real price list."' },
        { t: 'token', d: 'The unit models read and bill in — roughly three-quarters of a word. Input and output are priced separately per million tokens.', kid: 'Word-pieces. The computer reads and charges by the piece, like paying for sweets by weight.', use: '"That whole month of captions cost about forty cents in tokens — the margin is basically the whole fee."' },
        { t: 'context window', d: 'The maximum amount of text a model can consider in one request. Everything it "knows" about your situation must fit inside it.', kid: 'The size of the computer\'s desk. It can only think about what\'s on the desk right now.', use: '"The whole customer history fits in the context window, so it never asks him something he already answered."' },
        { t: 'prompt', d: 'The full input sent to a model: instructions, facts, and the user\'s message. The system prompt is the standing instruction that defines behaviour.', kid: 'The note you hand the robot before it starts work — who to be, what it knows, what never to do.', use: '"Most \'AI is dumb\' complaints are prompt problems — it was never given the shop\'s real hours."' },
        { t: 'hallucination', d: 'A model producing confident, plausible, false output — usually because the request could not be answered from what it was given.', kid: 'When the robot doesn\'t know, it makes up something that sounds right — like a kid guessing homework answers confidently.', use: '"We stop hallucinations the boring way: give it the real facts and a rule for saying I-don\'t-know."' },
        { t: 'inference', d: 'Running a trained model to get output. Distinct from training, which built the model. You only ever pay for inference.', kid: 'Training is teaching the robot (done once, costs millions). Inference is asking it questions (costs pennies). We only ask.', use: '"Training costs are the lab\'s problem — we just pay inference, which is cents."' },
        { t: 'fine-tuning', d: 'Further training a model on your own examples to change its default behaviour. Rarely worth it for small operators — prompting with good context usually wins.', kid: 'Sending the robot to a special extra class. Usually unnecessary — a better note (prompt) does the job.', use: '"You don\'t need fine-tuning for this — a tight system prompt with your data gets 95% of it."' },
        { t: 'API', d: 'Application Programming Interface — the plug that lets your code use someone else\'s service: send a request, get a response, pay per use.', kid: 'A vending machine for computer powers. Put in a request, get back the answer, pay per press.', use: '"The website talks to the AI through an API — no human in the middle, four-second answers at 2am."' },
        { t: 'API key', d: 'The secret credential that authorises API requests and ties them to your bill. Server-side only, always.', kid: 'The card that unlocks the vending machine — and everything bought with it goes on YOUR bill. Never leave it lying around.', use: '"The key lives on the server, never in the page — anyone can read a webpage\'s source."' },
        { t: 'agent', d: 'An AI system that takes actions in a loop — calling tools, reading results, deciding the next step — rather than answering once.', kid: 'A robot that doesn\'t just answer questions but actually does the chores: check the calendar, book the slot, send the text.', use: '"A chatbot answers; an agent books the appointment and texts the confirmation."' },
        { t: 'RAG', d: 'Retrieval-Augmented Generation — fetching relevant documents first and putting them in the prompt, so the model answers from your data instead of memory.', kid: 'Before the robot answers, it grabs the right page from your binder and reads from that.', use: '"It\'s RAG over their FAQ and price list, so every answer comes from their own documents."' },
        { t: 'multimodal', d: 'A model that handles more than text — images, audio, video — in and/or out.', kid: 'A robot that can see pictures and hear sound, not just read.', use: '"It\'s multimodal, so the shop just sends a photo of the board and it writes the post."' },
        { t: 'GPU / compute', d: 'The specialised chips AI runs on; "compute" is the general term for that processing capacity. The scarce, expensive layer of the industry.', kid: 'The super-fast engines the robots run on. Very expensive, which is why we rent instead of buy.', use: '"We\'re not buying compute — we rent inference by the token like everyone sensible."' },
        { t: 'open vs closed model', d: 'Open-weight models can be downloaded and run yourself; closed models are only reachable through the maker\'s API. Trade-off: control vs capability-per-effort.', kid: 'Some robots you can take home and keep; the strongest ones you can only visit and rent.', use: '"For this budget a closed model over the API beats hosting an open one — no server to babysit."' },
        { t: 'system prompt', d: 'The standing instruction block that defines a model\'s role, knowledge, style and hard rules — separate from the user\'s message, and where every safety rule belongs.', kid: 'The robot\'s job description, taped inside its head. Customers talk to it; they can\'t rewrite it.', use: '"The never-invent-a-price rule sits in the system prompt, so a clever customer can\'t talk it out of it."' },
        { t: 'rate limit', d: 'The cap on how many requests a service accepts from you per minute. Hitting it returns errors, not bigger bills.', kid: 'The vending machine only lets you press the button so many times a minute.', use: '"We rate-limit the public form too — twenty questions an hour per visitor keeps the bored teenagers off the bill."' }
      ]},

    { id: 'web', name: 'Web & hosting', icon: '🌐',
      blurb: 'The words that stop developers and hosting salesmen from quoting you fantasy prices.',
      terms: [
        { t: 'domain', d: 'The name people type — bought from a registrar for ~$10–15/year, pointed at hosting via DNS. You own the name, separately from the site.', kid: 'The shop\'s street address on the internet. You rent the address; the building is separate.', use: '"Keep the domain in YOUR registrar account, whoever builds the site — losing it is losing the business\'s address."' },
        { t: 'DNS', d: 'Domain Name System — the records that translate a domain into the servers that answer for it. Changing DNS re-points the name without moving the site.', kid: 'The internet\'s phone book. It tells browsers which computer answers when someone types the name.', use: '"It\'s a DNS change — the new site goes live by pointing the record, no rebuild needed."' },
        { t: 'hosting', d: 'Where the site\'s files actually live and get served from. Static hosting (files only) is effectively free; servers cost money and attention.', kid: 'The building the shop lives in. Ours is free because it\'s a simple building that never needs a caretaker.', use: '"Hosting costs us nothing — it\'s static on a free tier, so the care plan is nearly all margin."' },
        { t: 'SSL / HTTPS', d: 'The encryption layer (the padlock). Free and automatic on modern hosts; its absence marks a site as "Not secure" in browsers.', kid: 'The envelope that seals letters between the visitor and the site so nobody reads them in transit.', use: '"Their old site is still HTTP — Chrome literally labels it Not Secure to every customer. Day-one fix."' },
        { t: 'serverless function', d: 'Code that runs on demand per request with no server to maintain — free at low volume. How small products carry secrets and logic.', kid: 'A tiny worker who appears when a job arrives, does it, and vanishes. You pay per job, not per day.', use: '"The AI call runs in a serverless function — no server bill, and the key never touches the browser."' },
        { t: 'frontend / backend', d: 'Frontend: what runs in the visitor\'s browser (HTML/CSS/JS, fully visible to them). Backend: what runs on servers (logic, secrets, data).', kid: 'Frontend is the shop counter everyone sees. Backend is the office behind the door.', use: '"That form is frontend; the consent record is written by the backend so nobody can fake it."' },
        { t: 'database', d: 'Structured storage your product reads and writes — customers, orders, consents. Postgres is the standard; free tiers carry small businesses fine.', kid: 'A giant, organised filing cabinet the site can read and write really fast.', use: '"Every order lands in the database under the shop\'s slug, which is what turns a website into a system."' },
        { t: 'CDN', d: 'Content Delivery Network — copies of your static files cached in many cities so pages load fast everywhere. Free on modern hosts.', kid: 'Instead of one shop, tiny copies of it in every town, so it\'s always nearby and fast.', use: '"It\'s on a CDN, so it loads as fast in Phoenix as in Philly — matters more than people think for mobile."' },
        { t: 'responsive', d: 'A layout that adapts to screen size. Non-negotiable: most local traffic is phones.', kid: 'The site squishes and stretches to fit any screen, like water taking the shape of the glass.', use: '"Seventy-plus percent of their visits are phones — responsive isn\'t a feature, it\'s the site."' },
        { t: 'SEO', d: 'Search Engine Optimisation — making a site rank for the searches that matter. For local business it is mostly the Google Business Profile, reviews, and honest pages per service and town.', kid: 'Making sure that when someone asks Google "barber near me", Google answers with YOUR shop.', use: '"Local SEO here is 80% the Google profile and reviews — the fancy stuff comes after those are right."' },
        { t: 'analytics', d: 'Measurement of who visits and what they do. The point is decisions, not dashboards: which page leaks, which source converts.', kid: 'A counter on the door that also notices which shelf people stop at and where they give up.', use: '"Analytics says the booking page loses 60% on the phone-number field — that\'s the week\'s fix."' },
        { t: 'conversion rate', d: 'The share of visitors who take the action you wanted — book, call, join. The single most important number on any page.', kid: 'Out of 100 people who walk in, how many actually buy. Everything else is decoration.', use: '"Traffic is fine; conversion is 0.8%. We fix the page before we spend a dollar on more visitors."' },
        { t: 'cache', d: 'A saved copy used to answer repeat requests fast and cheap — browsers cache pages, CDNs cache files, APIs cache prompts.', kid: 'Instead of cooking the same meal every time, you keep one warm and serve it instantly.', use: '"The prompt prefix is cached, so repeat questions cost a fraction — check the cache-read number if bills look weird."' },
        { t: 'uptime', d: 'The percentage of time a service is reachable. "Three nines" (99.9%) is ~43 minutes of downtime a month.', kid: 'How often the shop\'s door is actually open when someone pulls the handle.', use: '"The stack is static-plus-managed-database precisely because its uptime is somebody else\'s full-time job."' },
        { t: 'deploy', d: 'Publishing a new version of the site or product. Modern flow: push code, host builds and ships it in under a minute, rollback is one click.', kid: 'Pressing the button that swaps the old shop window for the new one, everywhere at once.', use: '"I can deploy the fix in about a minute and roll it back just as fast if you hate it."' },
        { t: 'webhook', d: 'A URL that gets called automatically when something happens elsewhere — a payment lands, a form is filled — so systems react without polling.', kid: 'A doorbell between two programs: when something happens over there, it rings over here instantly.', use: '"When the form fires the webhook, the owner gets the text within the minute — that\'s the whole product."' }
      ]},

    { id: 'marketing', name: 'Marketing', icon: '📣',
      blurb: 'The working vocabulary of the trade you are selling. Owners can smell a tourist.',
      terms: [
        { t: 'funnel', d: 'The staged path from stranger to customer — reach, engage, capture, convert, retain — with a measurable rate at each step.', kid: 'A slide people go down: lots see you, fewer stop, fewer give their number, a few buy. You fix the step where most fall off.', use: '"Your funnel leaks at capture — people look and leave because there\'s no reason to hand over a number."' },
        { t: 'lead', d: 'A person who showed interest AND can be contacted. Attention without contact details is not a lead.', kid: 'Someone who raised their hand and told you where to find them.', use: '"That post got 40 likes and zero leads — likes can\'t be texted."' },
        { t: 'CTA', d: 'Call To Action — the one specific thing you ask the reader to do. One per piece; a menu of options is a leak.', kid: 'The "do this now" button. One button, not five.', use: '"The page has three CTAs fighting each other — we cut it to Book, said three times."' },
        { t: 'CAC', d: 'Customer Acquisition Cost — everything spent to win one customer, including your hours at a real rate.', kid: 'What it costs you, all-in, to get one new customer through the door.', use: '"Referrals run a CAC near zero, which is why the ask-after-a-win habit outearns any ad."' },
        { t: 'LTV', d: 'Lifetime Value — what a customer pays across the whole relationship. LTV against CAC is the health of the machine.', kid: 'Not what a customer spends today — what they spend over all the years they keep coming back.', use: '"A regular is a $600-a-year customer, so a $40 giveaway to win one is a bargain, not a cost."' },
        { t: 'churn', d: 'The rate at which customers leave. The silent number that decides whether growth compounds or refills a leaking bucket.', kid: 'The hole in the bucket. Pouring faster doesn\'t help until the hole shrinks.', use: '"Before we buy traffic we fix churn — new customers into a leaking bucket is renting revenue."' },
        { t: 'retention', d: 'Keeping the customers you have — repeat visits, loyalty, win-backs. Cheaper than acquisition by multiples, and almost always underworked.', kid: 'Getting the people who already came once to keep coming back. Way easier than finding strangers.', use: '"The retention play pays first: 80 lapsed regulars are worth more than any ad audience."' },
        { t: 'organic vs paid', d: 'Organic: attention earned without paying per view (content, SEO, referrals) — slow, compounding. Paid: bought per view — instant, stops when spend stops.', kid: 'Organic is planting a garden. Paid is buying vegetables. Both feed you; only one keeps feeding you.', use: '"We go organic-first so there\'s proof before spend — ads amplify a message that already works."' },
        { t: 'impressions / reach', d: 'Impressions: times content was shown. Reach: distinct people who saw it. Neither is a result; they are the top of the funnel.', kid: 'How many eyeballs passed the poster. Passing isn\'t buying.', use: '"Ten thousand impressions and no bookings means the hook works and the offer doesn\'t — different fix."' },
        { t: 'A/B test', d: 'Running two versions against each other with everything else equal, and letting the numbers pick. One change at a time or you learn nothing.', kid: 'Two posters, one difference, count which door gets more people. Now you KNOW instead of arguing.', use: '"We A/B the headline for a week — my taste and yours are both guesses; the click rate isn\'t."' },
        { t: 'copy', d: 'The words that sell — headlines, captions, texts, pages. The highest-leverage craft in marketing and the cheapest to improve.', kid: 'The words on everything. Changing the words changes how many people buy, without changing anything else.', use: '"Same page, new copy, capture went from 12 to 31 a week. Words are the cheapest renovation there is."' },
        { t: 'positioning', d: 'What you are, for whom, instead of what — chosen deliberately, so the market puts you in the right box before you speak.', kid: 'Deciding which shelf you sit on in people\'s heads: "the barbershop marketing guy", not "a marketer".', use: '"Positioning does the selling: \'the guy who does barbershops\' gets referred; \'a digital agency\' gets compared."' },
        { t: 'social proof', d: 'Evidence that others chose you — reviews, counts, named results. The nearer and more specific, the stronger.', kid: 'People check what other people did before deciding. A full restaurant looks tastier than an empty one.', use: '"Ray\'s went 8 to 43 reviews — that line closes more shops than my whole deck."' },
        { t: 'brand', d: 'What people expect from you before you speak — the accumulated residue of every touch. Built by consistency, spent by shortcuts.', kid: 'Your reputation, wearing a logo.', use: '"The brand play here is boring: same look, same promise, kept monthly, until the town just knows."' },
        { t: 'CRM', d: 'Customer Relationship Management — the system holding every contact, conversation and next step. The follow-up machine.', kid: 'A notebook that remembers everyone you talked to and taps your shoulder when it\'s time to call them back.', use: '"Every conversation gets a next-date in the CRM before I close the app — no date, it never happened."' },
        { t: 'niche', d: 'The specific market you serve. Specialists get referred, remembered and paid more than generalists.', kid: 'Picking ONE kind of customer to be famous with, instead of being a stranger to everyone.', use: '"The niche is barbershops — every script, sample and case study reloads for the next one."' }
      ]},

    { id: 'money', name: 'Money & business', icon: '💵',
      blurb: 'The vocabulary of people who get paid. Banks, clients and partners price you by these words.',
      terms: [
        { t: 'revenue', d: 'All money in, before any costs. The vanity line of the P&L.', kid: 'Everything that lands in the till, before you pay for anything.', use: '"Revenue\'s fine; the question is what\'s left after the tools and my hours — that\'s the real business."' },
        { t: 'margin', d: 'What remains after costs, as a share of price. Software-delivered services run margins agencies can only dream about.', kid: 'Sell for $10, costs you $2 to make — $8 margin. The gap is the business.', use: '"The loyalty product is ~95% margin — the software costs me nothing per shop."' },
        { t: 'recurring revenue (MRR)', d: 'Money that arrives monthly without re-selling — retainers, memberships. The difference between a business and a series of gigs.', kid: 'Money on repeat. You did the selling once and it keeps arriving while you sleep.', use: '"Six retainers is $1,800 MRR — I can plan a life on that; project work I\'d have to re-hunt monthly."' },
        { t: 'retainer', d: 'A fixed monthly fee for defined ongoing work, usually with 30 days\' notice either side. The standard vehicle for agency income.', kid: 'The client keeps you on the team monthly, like a gym membership for your services.', use: '"It\'s a $500 retainer, 30 days\' notice both ways — no lock-in, and no re-negotiating every month."' },
        { t: 'invoice', d: 'The formal request for payment: what, how much, by when. Sent before work starts for new clients, on the same date monthly for retainers.', kid: 'The bill. Sent proudly and on time, because favours don\'t pay rent.', use: '"Invoice goes out the 1st, report the day before — value first, charge second, renewal on autopilot."' },
        { t: 'cash flow', d: 'The timing of money in versus money out. Profitable businesses die of cash flow; timing is survival.', kid: 'Not how much money you make — WHEN it shows up versus when bills do. You can be rich on paper and broke on Tuesday.', use: '"Setup fees exist for cash flow — month one pays for itself instead of me floating the client."' },
        { t: 'overhead', d: 'Costs that run whether or not you sell anything — subscriptions, rent, salaries. The stack here is built to keep it near zero.', kid: 'The bills that arrive even if no customers do.', use: '"My overhead is a domain and a few subscriptions — a slow month hurts my pride, not my rent."' },
        { t: 'P&L', d: 'Profit and Loss statement — revenue minus costs over a period. The one page that says whether the business works.', kid: 'The scorecard: money in, money out, what\'s left.', use: '"One page, monthly: revenue, costs, profit. If I can\'t fill it in five minutes I don\'t know my own business."' },
        { t: 'break-even', d: 'The point where income covers costs. Knowing it per product tells you what survival requires.', kid: 'How many you have to sell before you stop losing money and start making it.', use: '"Break-even on the membership is two clients — everything past the second shop is profit."' },
        { t: 'equity vs fees', d: 'Fees pay now; equity pays maybe-later. Early on, fees — revenue compounds skills and runway; paper stakes mostly compound stories.', kid: 'Fees: money now. Equity: a slice of a pie that might never get baked. Eat first, collect slices later.', use: '"I\'ll take the fee, not the points — when there\'s revenue to share, we can revisit."' },
        { t: 'ROI', d: 'Return On Investment — what came back against what went in. The only frame in which your price sounds small.', kid: 'Put in $1, got back $4 — that\'s the whole conversation.', use: '"The win-back run cost $300 and brought back ~$1,100 — that ROI is the report\'s first line."' },
        { t: 'scope creep', d: 'Work quietly expanding past what was agreed, unpaid. Killed by written deliverables and a friendly change-order habit.', kid: 'You agreed to paint the fence; somehow you\'re re-roofing the house for the same money.', use: '"Happy to add that — it\'s outside the retainer, so I\'ll send a one-line change order first."' },
        { t: 'proposal', d: 'The written offer: the problem in their words, the plan, the deliverables, the price, the start date. Sent same-day while the conversation is warm.', kid: 'The plan and the price, written down, sent before they cool off.', use: '"You\'ll have the proposal tonight — if it reads right, we start Monday."' },
        { t: 'net terms', d: '"Net 30" means payment due 30 days after invoice. Fine for corporates; for small trade clients, due-on-receipt with auto-billing beats chasing.', kid: 'Fancy talk for "I\'ll pay you next month". Small shops pay now; big companies pay on terms.', use: '"Retainers auto-bill on the 1st — no net-30, no chasing, no awkward texts."' },
        { t: 'white-label', d: 'Selling software or services under your own brand while someone else runs the machinery. The client sees you; the supplier stays invisible.', kid: 'You sell the cake in your box with your name on it; the bakery stays out back.', use: '"Loop is white-label — the shop sees my brand, my number, my report. They\'re my client, full stop."' },
        { t: 'runway', d: 'How long you can operate before money runs out at current burn. The number that decides how bold you can afford to be.', kid: 'How many months you can keep going if nobody new pays you. Know it cold.', use: '"Overhead near zero means my runway is basically infinite — I can outlast every slow month."' }
      ]}
  ];

  w.TBU_VOCAB_XP = 15;   /* per deck, first perfect run — matches uni_xp_check() server-side */
})(window);
